from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import hashlib
import json
import re


def _slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (text or "").strip().lower()).strip("-")
    return s[:48] or "animationgen"


def emit_animation_bundle(prompt: str, content: str) -> Dict[str, Any]:
    key = hashlib.sha1(prompt.encode("utf-8")).hexdigest()[:12]
    root = Path("projects") / f"animation_{key}" / "animationgen" / _slug(prompt)
    root.mkdir(parents=True, exist_ok=True)

    shot_list_md = root / "SHOT_LIST.md"
    scene_beats_json = root / "scene_beats.json"
    prompt_package_json = root / "animation_prompt_package.json"
    readme_md = root / "README.md"

    shot_list_md.write_text(content, encoding="utf-8")

    scene_beats_json.write_text(
        json.dumps(
            {
                "prompt": prompt,
                "beats": [
                    {"shot": 1, "name": "Establishing shot", "purpose": "set location and mood"},
                    {"shot": 2, "name": "Subject introduction", "purpose": "introduce focal subject"},
                    {"shot": 3, "name": "Motion escalation", "purpose": "increase momentum"},
                    {"shot": 4, "name": "Close-up emphasis", "purpose": "highlight emotion or detail"},
                    {"shot": 5, "name": "Payoff frame", "purpose": "end on strongest visual"},
                ],
            },
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )

    prompt_package_json.write_text(
        json.dumps(
            {
                "prompt": prompt,
                "style": "cinematic stylized animation",
                "camera": "simple controlled movement",
                "continuity": "high asset reuse and visual consistency",
                "deliverables": [
                    "shot list",
                    "scene beat notes",
                    "animation prompt package",
                ],
            },
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )

    readme_md.write_text(
        f"""# Mythiq Animation Bundle

## Prompt
{prompt}

## Files
- `SHOT_LIST.md` - primary animation shot plan
- `scene_beats.json` - structured beat list
- `animation_prompt_package.json` - generation-ready package
- `README.md` - bundle notes

## Notes
Generated by Mythiq animation route.
""",
        encoding="utf-8",
    )

    files: List[str] = [
        str(shot_list_md),
        str(scene_beats_json),
        str(prompt_package_json),
        str(readme_md),
    ]

    return {
        "root": str(root),
        "files": files,
        "file_count": len(files),
    }
