from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List


def _safe_slug(title: str) -> str:
    s = "".join(ch.lower() if ch.isalnum() else "-" for ch in title).strip("-")
    while "--" in s:
        s = s.replace("--", "-")
    return s or "mythiq-project"


def _write(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return str(path)


def _game_files(root: Path, title: str) -> List[str]:
    out: List[str] = []

    out.append(_write(root / "README.md", f"""# {title}

Exportable browser game scaffold generated by Mythiq.

## Stack
- HTML
- CSS
- JavaScript

## Run
Open `index.html` in a browser for local preview.

## Next steps
- replace placeholder gameplay loop
- add save/load state
- add art/audio assets
- package for release
"""))

    out.append(_write(root / "index.html", f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{title}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <div class="wrap">
    <header class="top">
      <h1>{title}</h1>
      <p id="status">Mythiq scaffold ready</p>
    </header>
    <main class="game-shell">
      <canvas id="game" width="960" height="540"></canvas>
    </main>
    <section class="notes">
      <h2>Scaffold Notes</h2>
      <ul>
        <li>Core loop placeholder included</li>
        <li>Ready for progression and save-slot systems</li>
        <li>Extend in <code>src/main.js</code></li>
      </ul>
    </section>
  </div>
  <script type="module" src="src/main.js"></script>
</body>
</html>
"""))

    out.append(_write(root / "style.css", """html, body {
  margin: 0;
  padding: 0;
  background: #0f1115;
  color: #f5f7fa;
  font-family: Arial, sans-serif;
}
.wrap {
  max-width: 1100px;
  margin: 0 auto;
  padding: 24px;
}
.top {
  margin-bottom: 16px;
}
.game-shell {
  border: 1px solid #2a2f3a;
  background: #171a21;
  padding: 12px;
}
canvas {
  width: 100%;
  height: auto;
  background: #0b0d12;
  display: block;
}
.notes {
  margin-top: 20px;
}
code {
  background: #1d2330;
  padding: 2px 6px;
}
"""))

    out.append(_write(root / "src" / "main.js", """const canvas = document.getElementById("game");
const ctx = canvas.getContext("2d");

const state = {
  t: 0,
  phase: "boot",
  saveSlots: [{ id: 1, used: false }, { id: 2, used: false }, { id: 3, used: false }],
};

function render() {
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = "#8fb3ff";
  ctx.font = "28px Arial";
  ctx.fillText("Mythiq Game Scaffold", 40, 60);

  ctx.fillStyle = "#f5f7fa";
  ctx.font = "18px Arial";
  ctx.fillText(`Phase: ${state.phase}`, 40, 100);
  ctx.fillText(`Ticks: ${state.t}`, 40, 130);

  ctx.fillText("Save Slots:", 40, 190);
  state.saveSlots.forEach((slot, i) => {
    ctx.fillText(`Slot ${slot.id}: ${slot.used ? "USED" : "EMPTY"}`, 60, 225 + i * 28);
  });

  ctx.fillText("Next: add map, units, economy, persistence.", 40, 340);
}

function tick() {
  state.t += 1;
  if (state.t > 30) state.phase = "ready";
  render();
  requestAnimationFrame(tick);
}

tick();
"""))

    out.append(_write(root / "project.json", json.dumps({
        "type": "game",
        "engine": "web",
        "title": title,
        "generated_by": "Mythiq builder scaffold",
        "files": [
            "README.md",
            "index.html",
            "style.css",
            "src/main.js",
        ],
    }, indent=2)))

    return out


def _app_files(root: Path, title: str) -> List[str]:
    out: List[str] = []

    out.append(_write(root / "README.md", f"""# {title}

Browser app scaffold generated by Mythiq.

## Stack
- HTML
- CSS
- JavaScript

## Next steps
- connect UI state
- add persistence/api layer
- add auth if needed
- package deployment
"""))

    out.append(_write(root / "index.html", f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{title}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <div class="app">
    <header>
      <h1>{title}</h1>
      <p>Mythiq application scaffold</p>
    </header>
    <main>
      <section class="panel">
        <h2>Workspace</h2>
        <div id="output">Ready</div>
      </section>
    </main>
  </div>
  <script type="module" src="src/app.js"></script>
</body>
</html>
"""))

    out.append(_write(root / "style.css", """body {
  margin: 0;
  font-family: Arial, sans-serif;
  background: #0f1115;
  color: #f5f7fa;
}
.app {
  max-width: 1000px;
  margin: 0 auto;
  padding: 24px;
}
.panel {
  background: #171a21;
  border: 1px solid #2a2f3a;
  padding: 16px;
}
"""))

    out.append(_write(root / "src" / "app.js", """const out = document.getElementById("output");
out.textContent = "Mythiq app scaffold booted.";
"""))

    out.append(_write(root / "project.json", json.dumps({
        "type": "app",
        "title": title,
        "generated_by": "Mythiq builder scaffold",
    }, indent=2)))

    return out


def _media_files(root: Path, title: str) -> List[str]:
    out: List[str] = []

    out.append(_write(root / "README.md", f"""# {title}

Media project scaffold generated by Mythiq.

## Structure
- scripts/
- storyboards/
- assets/
- exports/

## Next steps
- add script beats
- add storyboard frames
- add render prompts
- export final bundle
"""))

    out.append(_write(root / "scripts" / "outline.md", f"""# {title} Outline

## Hook
Open with strongest emotional or visual claim.

## Middle
Escalate through 3-5 structured beats.

## Ending
Deliver payoff and loop back to the hook.
"""))

    out.append(_write(root / "storyboards" / "shotlist.md", """# Shot List

1. Establishing frame
2. Subject reveal
3. Escalation beat
4. Close-up emphasis
5. Payoff frame
"""))

    out.append(_write(root / "project.json", json.dumps({
        "type": "media",
        "title": title,
        "generated_by": "Mythiq builder scaffold",
    }, indent=2)))

    return out


def emit_builder_scaffold(project_id: str, project_spec: Dict[str, Any]) -> Dict[str, Any]:
    title = project_spec.get("title") or "Mythiq Project"
    target = project_spec.get("target") or "app"

    slug = _safe_slug(title)
    root = Path("projects") / project_id / "builder_scaffold" / slug

    if target == "game":
        files = _game_files(root, title)
    elif target == "media":
        files = _media_files(root, title)
    else:
        files = _app_files(root, title)

    manifest = {
        "project_id": project_id,
        "title": title,
        "target": target,
        "root": str(root),
        "file_count": len(files),
        "files": files,
    }

    manifest_path = root / "builder_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    return {
        "root": str(root),
        "manifest_path": str(manifest_path),
        "files": files,
        "file_count": len(files),
    }
