from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import hashlib
import re


def _slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (text or "").strip().lower()).strip("-")
    return s[:48] or "docsgen"


def emit_docs_bundle(prompt: str, content: str, goal: str) -> Dict[str, Any]:
    key = hashlib.sha1(prompt.encode("utf-8")).hexdigest()[:12]
    root = Path("projects") / f"docs_{key}" / "docsgen" / _slug(prompt)
    root.mkdir(parents=True, exist_ok=True)

    readme_md = root / "README.md"
    outline_md = root / "OUTLINE.md"
    summary_md = root / "SUMMARY.md"

    readme_md.write_text(content, encoding="utf-8")

    outline_md.write_text(
        f"""# Outline

## Goal
{goal}

## Sections
1. Title
2. Executive Summary
3. Problem / Opportunity
4. Proposed Direction
5. Execution Plan
6. Risks
7. Next Actions
""",
        encoding="utf-8",
    )

    summary_md.write_text(
        f"""# Summary

Prompt:
{prompt}

Goal:
{goal}

This bundle was generated by Mythiq docs generation.
""",
        encoding="utf-8",
    )

    files: List[str] = [str(readme_md), str(outline_md), str(summary_md)]
    return {
        "root": str(root),
        "files": files,
        "file_count": len(files),
    }
