from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import hashlib
import re


def _slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (text or "").strip().lower()).strip("-")
    return s[:48] or "textgen"


def emit_text_bundle(prompt: str, content: str) -> Dict[str, Any]:
    key = hashlib.sha1(prompt.encode("utf-8")).hexdigest()[:12]
    root = Path("projects") / f"text_{key}" / "textgen" / _slug(prompt)
    root.mkdir(parents=True, exist_ok=True)

    response_md = root / "RESPONSE.md"
    summary_md = root / "SUMMARY.md"
    metadata_json = root / "metadata.json"

    response_md.write_text(content, encoding="utf-8")

    summary_md.write_text(
        f"""# Mythiq Text Bundle

## Prompt
{prompt}

## Notes
- direct response
- reusable text artifact
- generated by Mythiq
""",
        encoding="utf-8",
    )

    metadata_json.write_text(
        """{
  "type": "text_bundle",
  "format": "markdown",
  "intent": "direct_response"
}
""",
        encoding="utf-8",
    )

    files: List[str] = [str(response_md), str(summary_md), str(metadata_json)]
    return {
        "root": str(root),
        "files": files,
        "file_count": len(files),
    }
