from __future__ import annotations

from typing import Any, Dict

from api.app.core.models import FeatureResult, PlanOut, PlanStep


def plan(inp: Dict[str, Any]) -> PlanOut:
    return PlanOut(
        feature="code",
        steps=[
            PlanStep(id="c1", action="analyze_task"),
            PlanStep(id="c2", action="generate_patch_or_scaffold"),
            PlanStep(id="c3", action="add_validation_notes"),
        ],
    )


def run(inp: Dict[str, Any], reused_pattern: str | None = None) -> FeatureResult:
    prompt = inp["prompt"].strip()

    code = f'''# generated by Mythiq
def solve():
    """
    Task: {prompt}
    Pattern: {reused_pattern or "default_code_v1"}
    """
    return {{
        "ok": True,
        "message": "Implement concrete business logic here"
    }}

if __name__ == "__main__":
    print(solve())
'''

    return FeatureResult(
        ok=True,
        feature="code",
        type="python",
        content=code,
        files=[],
        meta={"pattern_used": reused_pattern or "default_code_v1"},
    )
