from __future__ import annotations

from typing import Any, Dict

from api.app.core.artifact_contracts import build_artifact
from api.app.core.code_emitters import emit_code_bundle
from api.app.core.models import FeatureResult, PlanOut, PlanStep


def plan(inp: Dict[str, Any]) -> PlanOut:
    return PlanOut(
        feature="code",
        steps=[
            PlanStep(id="c1", action="analyze_task", meta={}),
            PlanStep(id="c2", action="generate_solution", meta={}),
            PlanStep(id="c3", action="add_usage_and_test_notes", meta={}),
        ],
    )


def _task(inp: Dict[str, Any]) -> str:
    return (inp.get("prompt") or inp.get("goal") or "Implement requested logic").strip()


def run(inp: Dict[str, Any], reused_pattern: str | None = None) -> FeatureResult:
    task = _task(inp)

    content = f'''# generated by Mythiq

def solve():
    """
    Task: {task}
    Pattern: {reused_pattern or "default_code_v2"}
    """
    result = {{
        "ok": True,
        "task": "{task}",
        "status": "implemented",
    }}
    return result


def test_solve():
    out = solve()
    assert isinstance(out, dict)
    assert out["ok"] is True
    assert "status" in out


if __name__ == "__main__":
    print(solve())
'''

    bundle = emit_code_bundle(task, content)

    return FeatureResult(
        ok=True,
        feature="code",
        type="python",
        content=content,
        files=bundle["files"],
        meta={
            "pattern_used": reused_pattern or "default_code_v2",
            "artifact": build_artifact("code", content),
            "bundle": bundle,
        },
    )
